services:
    plausible.admin:
        class: Pixel\PlausibleBundle\Admin\PlausibleAdmin
        autowire: false
        arguments:
            - '@sulu_admin.view_builder_factory'
            - '%plausible.domain%'
            - '%plausible.base_url%'
            - '%plausible.auth_key%'
        tags:
            - { name: sulu.admin, alias: plausible }